version: '3.3'
services:
    mysql:
        image: mysql:8.0
        command:
            - mysqld
            - "--default-authentication-plugin=mysql_native_password"
        environment:
            - MYSQL_ROOT_PASSWORD=doctrine
            - MYSQL_DATABASE=doctrine
            - MYSQL_USER=doctrine
            - MYSQL_PASSWORD=doctrine
    php:
        build:
            context: ./php
            args:
                - "XDEBUG_REMOTE_HOST=host.docker.internal"
        command:
            - bash
            - "-c"
            - if [[ -d /var/www/symfony.new && ! -d /var/www/symfony/public ]]; then echo 'initializing symfony setup'; echo 'waiting for mysql to start (30 seconds)'; sleep 30; echo 'done waiting for mysql'; pushd /var/www/symfony.new; cp -Rp * ../symfony; cp -Rp .??* ../symfony; php bin/console doctrine:migrations:migrate --no-interaction; popd; echo done; fi; php-fpm
        links:
            - mysql
        volumes:
            - "doctrine-symfony:/var/www/symfony"
        working_dir: /var/www/symfony
        depends_on:
            - mysql
    nginx:
        image: nginx:1.17
        volumes:
            - ./nginx/${NGINX_TEMPLATE}:/etc/nginx/conf.d/default.conf
            - "doctrine-symfony:/var/www/symfony"
        links:
            - php
        ports:
            - "8089:80"
        depends_on:
            - php
        command: nginx -g 'daemon off;'
volumes:
    doctrine-symfony:
