version: '3.3'
services:
    mongo:
        image: mongo:3.5
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    php:
        build:
            context: ./php
            args:
                - "XDEBUG_REMOTE_HOST=${DOCKERHOST}"
        links:
            - mysql
            - mongo
            - redis
        volumes:
            - "${SYMFONY_ROOT}:/var/www/symfony"
        working_dir: /var/www/symfony
        depends_on:
            - mysql
            - mongo
            - redis
    nginx:
        image: nginx:1.13.1
        volumes:
            - ./nginx/symfony.template:/etc/nginx/conf.d/default.conf
            - "./src:/var/www/symfony"
        links:
            - php
        ports:
            - "8081:80"
        depends_on:
            - php
        command: nginx -g 'daemon off;'
    redis:
        image: redis:4.0