version: '3.3'
services:
    mongo:
        image: mongo:4.0
    postgres:
        image: postgres:11
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    php:
        build:
            context: ./php
            args:
                - "XDEBUG_REMOTE_HOST=${DOCKERHOST}"
        links:
            - mysql
            - mongo
            - redis
        volumes:
            - "${SYMFONY_ROOT}:/var/www/symfony"
        working_dir: /var/www/symfony
        depends_on:
            - mysql
            - postgres
            - mongo
            - redis
    nginx:
        image: nginx:1.17
        volumes:
            - ./nginx/${NGINX_TEMPLATE}:/etc/nginx/conf.d/default.conf
            - "${SYMFONY_ROOT}:/var/www/symfony"
        links:
            - php
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - php
        command: nginx -g 'daemon off;'
    redis:
        image: redis:5.0
